apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  allowedListeners:
    namespaces:
      from: All
  addresses:
  - type: IPAddress
    value: "192.168.1.210"
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: test-https
    protocol: HTTPS
    port: 443
    hostname: test.codesugar.mx
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: test-codesugar-mx-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: test2-https
    protocol: HTTPS
    port: 443
    hostname: test2.codesugar.mx
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: test2-codesugar-mx-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: ldap-https
    protocol: HTTPS
    port: 443
    hostname: ldap.codesugar.mx
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: ldap-codesugar-mx-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: webhook-flux-https
    protocol: HTTPS
    port: 443
    hostname: webhook-flux.codesugar.mx
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: webhook-flux-codesugar-mx-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: jellyfin-https
    protocol: HTTPS
    port: 443
    hostname: jellyfin.codesugar.mx
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: jellyfin-codesugar-mx-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: forejo-https
    protocol: HTTPS
    port: 443
    hostname: git.codesugar.mx
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: forejo-codesugar-mx-tls
    allowedRoutes:
      namespaces:
        from: All
